# Create a Kubernetes Service for MySQL
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
    app: worpress-app
spec:
  selector:
    name: mysql-pod
    app: worpress-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
