apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-mysql-pv-claim
  labels:
    app: database-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi