# Create a Kubernetes configmap for MySQL
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: mysql-configmap
  labels:
    app: wordpress
data:
  MYSQL_DATABASE: "testdatabase"
  MYSQL_USERNAME: "testuser"
  MYSQL_PASSWORD: "testpassword"
  MYSQL_RANDOM_ROOT_PASSWORD: "1"