# Create a Kubernetes Deployment for MySQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          # env:
          #   - name: MYSQL_DATABASE
          #     valueFrom:
          #       configMapKeyRef:
          #         key: MYSQL_DATABASE
          #         name: mysql-configmap
          #   - name: MYSQL_USERNAME
          #     valueFrom:
          #       configMapKeyRef:
          #         key: MYSQL_USERNAME
          #         name: mysql-configmap
          #   - name: MYSQL_PASSWORD
          #     valueFrom:
          #       configMapKeyRef:
          #         key: MYSQL_PASSWORD
          #         name: mysql-configmap
          #   - name: MYSQL_RANDOM_ROOT_PASSWORD
          #     valueFrom:
          #       configMapKeyRef:
          #         key: MYSQL_RANDOM_ROOT_PASSWORD
          #         name: mysql-configmap
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: asdfg
            - name: MYSQL_DATABASE
              value: testdatabase
            - name: MYSQL_USERNAME
              value: testuser
            - name: MYSQL_PASSWORD
              value: testpassword
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim