apiVersion: "v1"
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: wordpress
type: Opaque
data:
  MYSQL_DATABASE: TVlTUUxfREFUQUJBU0U=
  MYSQL_USERNAME: TVlTUUxfVVNFUk5BTUU=
  MYSQL_PASSWORD: TVlTUUxfUEFTU1dPUkQ=
  MYSQL_RANDOM_ROOT_PASSWORD: TVlTUUxfUkFORE9NX1JPT1RfUEFTU1dPUkQ=

# echo -n 'MYSQL_RANDOM_ROOT_PASSWORD' | base64
  