apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 3306
    targetPort: 3306
  type: ExternalName
  externalName: ${}
