# Create a Kubernetes Service for MySQL
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      nodePort: 30036
      targetPort: 3306
  type: NodePort
