version: '3.1'

services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: test
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: test
    volumes: 
      - ./:/var/www/html
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app_network

volumes:
  db:

networks:
  app_network:
    driver: bridge
    name: wordpress-network
