version: '3.1'

services:
  webserver:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  wordpress:
    depends_on:
      - php
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database-1.c4v46hctkald.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USERNAME: test
      WORDPRESS_DB_PASSWORD: Ifiekemi1990
      WORDPRESS_DB_NAME: test
    volumes: 
      - ./:/var/www/html
    networks:
      - app_network
    labels:
      kompose.service.type: LoadBalancer

networks:
  app_network:
    driver: bridge
    name: wordpress-network