version: '3.1'

services:
  webserver:
    image: nginx:${NGINX_VERSION}
    container_name: ${NGINX_CONTAINER}
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - app_network

  wordpress:
    depends_on: 
      - mysql-service
    image: wordpress:${WORDPRESS_VERSION}
    container_name: ${WORDPRESS_CONTAINER}
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql-service:3306
      WORDPRESS_DB_USERNAME: test
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    volumes: 
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - app_network
    labels:
      kompose.service.type: LoadBalancer

  mysql-service:
    image: mysql:${DB_VERSION}
    container_name: ${DB_CONTAINER}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${RANDOM_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    ports: 
      - 3306
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app_network

volumes:
  db:

networks:
  app_network:
    driver: bridge
    name: wordpress-network
