version: '3.1'

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - app_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    volumes: 
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: wordpress-network
