version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: "${DB_ENDPOINT}:${DB_PORT}"
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
    volumes: 
      - wp_data:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    name: wordpress-network

volumes:
  wp_data:
