#pip
version: 2.1

orbs:
  slack: circleci/slack@4.10.1
  aws-cli: circleci/aws-cli@3.1.4
  kubernetes: circleci/kubernetes@1.0.2

commands:
  notify_on_failure:
    steps:
      - slack/notify:
          event: fail
          channel: cicd-pipeline
          template: basic_fail_1

# INSTALL  DEPENDENCIES
  install_awscli:
    description: Install AWS CLI v2
    steps:
      - run:
          name: Install AWS CLI v2
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

  install_docker_engine:
    description: Install AWS CLI v2
    steps:
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '2.19.0'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose


  install_docker_compose_cli:
    description: Install AWS CLI v2
    steps:
     - run:
          name: Install Docker Compose CLI plugin
          command: |
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            sudo mkdir -p $DOCKER_CONFIG/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            sudo chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

# DESTROY ENVIRONMENTS
  destroy_vpc_stack_environment:
    description: Destroy VPC cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
        default: "${CIRCLE_WORKFLOW_ID:0:7}"
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws cloudformation delete-stack --stack-name wordpress-vpc-stack-<< parameters.workflow_id >>

  destroy_rds_stack_environment:
    description: Destroy RDS cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
        default: "${CIRCLE_WORKFLOW_ID:0:7}"
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws cloudformation delete-stack --stack-name wordpress-rds-stack-<< parameters.workflow_id >>

  destroy_eks_stack_environment:
    description: Destroy EKS cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string
        default: "${CIRCLE_WORKFLOW_ID:0:7}"
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws cloudformation delete-stack --stack-name wordpress-eks-stack-<< parameters.workflow_id >>

jobs:
  syntax_validation:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip
      - run:
          name: Run Syntax Validation
          command: |
            set -e

            for file in *.php 
            do
                if ! php -l "$file"; then
                    echo "Syntax error in $file"
                    exit 1
                fi
            done

      # - notify_on_failure

# DEPLOY INFRASTRUCTURE
  deploy_vpc_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Provision network infrastructure
          command: |
            aws cloudformation deploy \
              --template-file iac/cloudformation/vpc-stack.yml \
              --tags project=wordpress-project \
              --stack-name "wordpress-vpc-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides file://iac/cloudformation/vpc-parameters.json \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

      # - notify_on_failure
      - destroy_vpc_stack_environment


  deploy_rds_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Provision Database Instance
          no_output_timeout: 30m
          command: |
            aws cloudformation deploy \
              --template-file iac/cloudformation/rds-stack.yml \
              --tags project=wordpress-project \
              --stack-name "wordpress-rds-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides file://iac/cloudformation/rds-parameters.json \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

      # - notify_on_failure
      - destroy_rds_stack_environment

  get_rds_endpoint:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install tar utility to have workflow workspace capability
          command: |
            yum install -y tar gzip
      - run:
          name: Get Database Instance Endpoint annd save in a vaiable
          command: |
            export DB_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier ${DB_INSTANCE_IDENTIFIER} \
            --query 'DBInstances[*].Endpoint.Address' \
            --output text)

            echo ${DB_ENDPOINT} > .env
            echo ${DB_ENDPOINT}
            cat .env

      - persist_to_workspace:
          root: ~/
          paths:
            - project/.env

      # - notify_on_failure
      # - destroy_rds_stack_environment

  deploy_eks_stack:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Set up Kubernetes Cluster
          no_output_timeout: 30m
          command: |
            aws cloudformation deploy \
              --template-file iac/cloudformation/eks-stack.yml \
              --tags project=wordpress-project \
              --stack-name "wordpress-eks-stack-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides file://iac/cloudformation/eks-parameters.json \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

#       - notify_on_failure
      - destroy_eks_stack_environment

# BUILD APPLICATION
  build_app:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - install_awscli
      - install_docker_compose_cli
      - setup_remote_docker
      - run:
          name: Get Database Instance Endpoint annd save in a vaiable
          command: |
            export DB_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier ${DB_INSTANCE_IDENTIFIER} \
            --query 'DBInstances[*].Endpoint.Address' \
            --output text)

            echo ${DB_ENDPOINT} > .env
            echo ${DB_ENDPOINT}
            cat .env

      - run:
          name: Build and Start all services declared in docker-compose.yml
          command: |
            docker-compose up -d docker-compose up -d --env-file .env
            # docker inspect -f "{{.Name}} {{.Config.Env}}" wordpress

      # - run:
      #     name: Push to Docker Hub
      #     command: |
      #       echo "$DOCKER_PASSWORD"
      #       docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #       docker tag $WORDPRESS_IMAGE:latest $DOCKER_USERNAME/$WORDPRESS_IMAGE
      #       docker push $DOCKER_USERNAME/$WORDPRESS_IMAGE

      - persist_to_workspace:
          root: ~/
          paths:
            - project/.env

            
#       - notify_on_failure

#   # DEPLOY APPLICATION
#   deploy_app:
#     docker:
#       - image: cimg/python:3.10
#     steps:
#       - checkout
#       - install_awscli
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Install kubectl
#           command: |
#             curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#             chmod +x ./kubectl
#             sudo mv ./kubectl /usr/local/bin/kubectl
#             aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
#             kubectl apply -f operations/wordpress/

#             kubectl get deployments -w

#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - project/.env

#       - notify_on_failure







workflows:
  wordpress-workflow:
    jobs:
      # - syntax_validation
      # - deploy_vpc_stack:
      #     requires: [syntax_validation]
      # - deploy_rds_stack:
          # requires: [deploy_vpc_stack]
      # - get_rds_endpoint:
          # requires: [deploy_rds_stack]
      # - deploy_eks_stack:
          # requires: [deploy_vpc_stack]
        - build_app
        #     requires: [get_rds_endpoint]
        # - deploy_app:
        #     requires: [build_app]

      # - run:
      #     name: Start docker-compose and verify service(s)
      #     command: |
      #       # Setting the Docker Compose project name to "circleci-demo-docker" means
      #       # the names of our services' containers would be prefixed with "circleci-demo-docker".
      #       docker-compose --project circleci-demo-docker up -d

      #       # In this example, we have a "contacts" service, and
      #       # we are trying to check, via `dockerize`, if the service is ready.
      #       docker container run --network container:circleci-demo-docker_contacts_1 \
      #         docker.io/jwilder/dockerize \
      #         -wait http://localhost:8080/healthcheck \
      #         -wait-retry-interval 2s \
      #         -timeout 20s
