apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer


  
