apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: maiempire/wordpress:latest
          env:
            # - name: WORDPRESS_DB_HOST
            #   value: mysql-service
            # - name: WORDPRESS_DB_USER
            #   valueFrom:
            #     secretKeyRef:
            #       key: WORDPRESS_DB_USER
            #       name: wordpress-secret
            # - name: WORDPRESS_DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       key: WORDPRESS_DB_PASSWORD
            #       name: wordpress-secret
            # - name: WORDPRESS_DB_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       key: WORDPRESS_DB_NAME
            #       name: wordpress-secret
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_HOST
                  name: wordpress-configmap
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_USER
                  name: wordpress-configmap
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_PASSWORD
                  name: wordpress-configmap
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_NAME
                  name: wordpress-configmap
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim

