---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
data:
  WORDPRESS_DB_HOST: <base64-encoded-value>
  WORDPRESS_DB_USER: <base64-encoded-value>
  WORDPRESS_DB_PASSWORD: 
  WORDPRESS_DB_NAME: 
