---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_HOST
                  name: wordpress-config
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_USER
                  name: wordpress-config
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_PASSWORD
                  name: wordpress-config
          # env:
          #   - name: WORDPRESS_DB_HOST
          #     value: mysql-service
          #   - name: WORDPRESS_DB_PASSWORD
          #     value: your_mysql_db_password
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
