apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  labels:
    app: wordpress
data:
  # WORDPRESS_DB_HOST: mysql-service.default.svc.cluster.local
  WORDPRESS_DB_USER: ${DB_USERNAME}
  WORDPRESS_DB_NAME: ${DB_DATABASE}
  WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
  WORDPRESS_DB_HOST: ${DB_ENDPOINT}