---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: postgres
data:
  WORDPRESS_DB_HOST: ""
  WORDPRESS_DB_USER: ""
  WORDPRESS_DB_PASSWORD: ""
  WORDPRESS_DB_NAME: ""