---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    name: wordpress-deployment
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-pod
      app: wordpress-app
  template:
    metadata:
      name: wordpress-pod
      labels:
        name: wordpress-pod
        app: wordpress-app
    spec:
      containers:
        - name: wordpress
          image: maiempire/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_HOST
                  name: wordpress-configmap
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_USER
                  name: wordpress-configmap
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_PASSWORD
                  name: wordpress-configmap
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: WORDPRESS_DB_NAME
                  name: wordpress-configmap
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim

