apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: maiempire/wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: ${DB_HOST}
        - name: WORDPRESS_DB_PASSWORD
          VALUE: ${DB_PASSWORD}
        - name: WORDPRESS_DB_NAME
          value: ${DB_NAME}
        - name: WORDPRES_DB_USERNAME
          value: ${DB_USERNAME}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc

