---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: {{ .Values.env.DB_USERNAME }}
  WORDPRESS_DB_PASSWORD: {{ .Values.env.DB_PASSWORD }}
  WORDPRESS_DB_NAME: {{ .Values.env.DB_DATABASE }}

