---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: "admin"
  WORDPRESS_DB_PASSWORD: "xLeqcHzdapQvnyYvdJlw"
  WORDPRESS_DB_NAME: "wordpress"

