---
apiVersion: "v1"
kind: ConfigMap
metadata:
  name: wordpress-config
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: "database-1.c4v46hctkald.us-east-1.rds.amazonaws.com"
  WORDPRESS_DB_USER: "admin"
  WORDPRESS_DB_PASSWORD: "xLeqcHzdapQvnyYvdJlw"
  WORDPRESS_DB_NAME: "wordpress"