# Create a Kubernetes configmap for Nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels:
    app: wordpress
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    server {
        listen 80;
        server_name localhost;
        root /var/www/html;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        }
    }


#     http {
#       server {
#         listen 80;
#         server_name localhost;
#         location / {
#           root /usr/share/nginx/html;
#           index index.html index.htm;
#         }
#       }
#     }