apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
          - name: nginx-configmap
            mountPath: /etc/nginx/conf.d/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-configmap
          configMap:
            name: nginx-configmap